/**
 * Rebuilds every derived view: knowledge/INDEX.md (for humans and for AI
 * retrieval) and state/index.json (for the scheduler and briefing).
 *
 * Both are disposable. Delete them and run `npm run index` to get them back.
 */

import { ITEM_TYPES } from './types.ts';
import type { Item, ItemMeta } from './types.ts';
import { loadAllItems } from './item.ts';
import { paths, writeFile, writeJson, today } from './util.ts';

export function rebuildIndex(items: Item[] = loadAllItems()): Item[] {
  writeJson(paths.stateIndex, {
    generated: today(),
    count: items.length,
    items: items.map(({ body: _body, ...meta }): ItemMeta => meta),
  });
  writeFile(paths.knowledgeIndex, renderIndexMarkdown(items));
  return items;
}

function renderIndexMarkdown(items: Item[]): string {
  const now = today();
  const lines: string[] = [
    '# Knowledge Index',
    '',
    `> Generated by \`npm run index\` on ${now}. Do not edit by hand.`,
    '',
    `**${items.length}** items · ` +
      (['new', 'learning', 'familiar', 'mastered'] as const)
        .map((s) => `${s}: ${items.filter((i) => i.status === s).length}`)
        .join(' · '),
    '',
  ];

  for (const type of ITEM_TYPES) {
    const group = items.filter((i) => i.type === type);
    if (group.length === 0) continue;

    lines.push(`## ${type} (${group.length})`, '');
    lines.push('| id | title | domain | status | mastery | next review |');
    lines.push('|---|---|---|---|---|---|');
    for (const i of group.sort((a, b) => a.title.localeCompare(b.title))) {
      const due = i.next_review <= now ? `**${i.next_review}**` : i.next_review;
      lines.push(
        `| \`${i.id}\` | ${i.title} | ${i.domain.join(', ')} | ${i.status} | ` +
          `${i.mastery_score.toFixed(2)} | ${due} |`,
      );
    }
    lines.push('');
  }

  if (items.length === 0) {
    lines.push('_No items yet. Run `npm run ingest <session-report.md>` to add some._', '');
  }

  return lines.join('\n');
}
